language: php

php:
    - 5.3
    - 5.4
    - 5.5

before_script:
    - composer install
    - mkdir -p build/logs
    
script:
    phpunit --configuration phpunit.xml tests

after_script:
    - php vendor/bin/coveralls -v